### ISSUE TITLE
Does this work with standard neomutt?

### ISSUE THREAD

**Issue by maitra** [lbrayner/config_neomutt#3]
Does this config file work with the regular neomutt or only your fork? Thanks!

**Comment by lbrayner** [comment]
Yes, it does.

Just be aware that some macros call scripts that are located in the vendor folder -- and some scripts call other scripts in there. I've realized recently that one of them calls a script (iconvert) that is not available in this repository, but it's in another one (https://github.com/lbrayner/shell_scripts). 

The colorscheme is in a submodule. After cloning this repository, just run `git submodule update --init`.

**Comment by lbrayner** [comment]
This has been incorporated into [neomutt](https://github.com/neomutt/neomutt) via https://github.com/neomutt/neomutt/commit/cc33407dc61d871e02edd813fb24b15ef544bc9f.
